# Generated by Django 4.1.1 on 2023-08-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="empresas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveBigIntegerField()),
                ("nombre_empresa", models.CharField(max_length=30)),
                ("direccion_ip", models.CharField(max_length=100)),
                ("usuario", models.CharField(max_length=100)),
                ("clave_acceso", models.CharField(max_length=100)),
            ],
        ),
    ]
