# Generated by Django 4.1.1 on 2023-08-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0003_rename_numero_empresas_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresas",
            name="ref_cartera",
            field=models.CharField(default="MATRIZ", max_length=30),
        ),
    ]
