# Generated by Django 4.1.1 on 2023-08-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("dashboards", "0004_empresas_ref_cartera"),
    ]

    operations = [
        migrations.CreateModel(
            name="usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name="empresas",
            name="ref_cartera",
            field=models.CharField(default="*", max_length=30),
        ),
        migrations.CreateModel(
            name="OpcionMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("vista", models.CharField(max_length=100)),
                ("icono", models.CharField(max_length=50)),
                ("permisos", models.ManyToManyField(to="auth.permission")),
            ],
        ),
    ]
