# Generated by Django 4.1.1 on 2023-08-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0005_usuarios_alter_empresas_ref_cartera_opcionmenu"),
    ]

    operations = [
        migrations.RemoveField(model_name="opcionmenu", name="permisos",),
        migrations.RemoveField(model_name="usuarios", name="usuario",),
        migrations.AddField(
            model_name="usuarios",
            name="nombre",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usuarios",
            name="opciones_menu",
            field=models.ManyToManyField(to="dashboards.opcionmenu"),
        ),
    ]
