# Generated by Django 4.1.1 on 2023-08-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboards",
            "0006_remove_opcionmenu_permisos_remove_usuarios_usuario_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(old_name="usuarios", new_name="Permisos",),
    ]
