# Generated by Django 4.1.1 on 2023-08-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboards",
            "0009_opcionmenuvta_rename_opcionmenu_opcionmenupostvta_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(old_name="OpcionMenupostvta", new_name="OpcionMenu",),
        migrations.RenameField(
            model_name="permisos",
            old_name="opcion_defaultpostvta",
            new_name="opcion_default",
        ),
        migrations.RenameField(
            model_name="permisos",
            old_name="opciones_menupostvta",
            new_name="opciones_menu",
        ),
        migrations.RemoveField(model_name="permisos", name="opcion_defaultvta",),
        migrations.RemoveField(model_name="permisos", name="opciones_menuvta",),
        migrations.DeleteModel(name="OpcionMenuvta",),
    ]
