# Generated by Django 4.1.1 on 2023-08-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0011_opcionmenupostvta_permisospostvta"),
    ]

    operations = [
        migrations.RemoveField(model_name="permisospostvta", name="opcion_default",),
        migrations.RemoveField(model_name="permisospostvta", name="opciones_menu",),
        migrations.DeleteModel(name="OpcionMenupostvta",),
        migrations.DeleteModel(name="PermisosPostvta",),
    ]
