# Generated by Django 4.1.1 on 2023-08-22 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0007_rename_usuarios_permisos"),
    ]

    operations = [
        migrations.AddField(
            model_name="permisos",
            name="opcion_default",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permiso_default_relacionado",
                to="dashboards.opcionmenu",
            ),
        ),
    ]
