# Generated by Django 4.1.1 on 2023-08-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresas",
            name="sucursal",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
