# Generated by Django 4.2.3 on 2023-09-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_postventa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='empresas',
        ),
        migrations.AlterModelOptions(
            name='opcionmenu',
            options={'ordering': ['orden'], 'verbose_name': 'Opciones del menu'},
        ),
        migrations.AlterModelOptions(
            name='permisos',
            options={'verbose_name': 'Permisos x usuario'},
        ),
        migrations.AddField(
            model_name='opcionmenu',
            name='orden',
            field=models.IntegerField(default=0, help_text='Indica el orden en que se mostrara en el menu'),
        ),
    ]
