# Generated by Django 4.1.1 on 2023-08-23 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0008_permisos_opcion_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpcionMenuvta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("vista", models.CharField(max_length=100)),
                ("icono", models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(old_name="OpcionMenu", new_name="OpcionMenupostvta",),
        migrations.RenameField(
            model_name="permisos",
            old_name="opcion_default",
            new_name="opcion_defaultpostvta",
        ),
        migrations.RenameField(
            model_name="permisos",
            old_name="opciones_menu",
            new_name="opciones_menupostvta",
        ),
        migrations.AddField(
            model_name="permisos",
            name="opcion_defaultvta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permiso_default_relacionado",
                to="dashboards.opcionmenuvta",
            ),
        ),
        migrations.AddField(
            model_name="permisos",
            name="opciones_menuvta",
            field=models.ManyToManyField(to="dashboards.opcionmenuvta"),
        ),
    ]
