# Generated by Django 4.1.1 on 2023-08-23 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0010_rename_opcionmenupostvta_opcionmenu_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpcionMenupostvta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("vista", models.CharField(max_length=100)),
                ("icono", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PermisosPostvta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "opcion_default",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permiso_default_relacionado",
                        to="dashboards.opcionmenupostvta",
                    ),
                ),
                (
                    "opciones_menu",
                    models.ManyToManyField(to="dashboards.opcionmenupostvta"),
                ),
            ],
        ),
    ]
