# Generated by Django 4.1.1 on 2023-08-23 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="empresas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.PositiveBigIntegerField()),
                ("sucursal", models.PositiveBigIntegerField(default=1)),
                ("nombre_empresa", models.CharField(max_length=30)),
                ("direccion_ip", models.CharField(max_length=100)),
                ("usuario", models.CharField(max_length=100)),
                ("clave_acceso", models.CharField(max_length=100)),
                ("ref_cartera", models.CharField(default="*", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="OpcionMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("vista", models.CharField(max_length=100)),
                ("icono", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Permisos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "opcion_default",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permiso_default_relacionado",
                        to="app_postventa.opcionmenu",
                    ),
                ),
                (
                    "opciones_menu",
                    models.ManyToManyField(to="app_postventa.opcionmenu"),
                ),
            ],
        ),
    ]
