# Generated by Django 4.1.1 on 2023-08-12 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminlte3", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="empresas",),
    ]
